version: "3.9"
services:
  booking:
    image: booking_service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/booking_db

  postgres:
    container_name: bookingPG
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "booking_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "54321"
    ports:
      - "5432:5432"